Feat: Indicator
margelo/react-native-graph pull request #21
Opened 2022-06-13 09:43 UTC by chrispader

Allow the user to show an indicator at the end of the graph. This indicator gets hidden once the hold/pan gesture gets started.

2022-06-13 09:44 UTC, chrispader commented
@mrousavy Ready for review! This PR is based on #17 and #18.

2022-07-02 21:04 UTC, gtokman commented
@chrispader do you have a video example of what the indicator looks like? Wondering what the use case would be!

2022-07-02 21:24 UTC, chrispader commented
This is how it looks in the app i originally had the need for this feature.

This includes the basic indicator and also a "live" pulse animation.

https://user-images.githubusercontent.com/20173411/177016519-4513ee97-0bf8-4bc8-ac5d-2ed005638ecb.MOV

2022-07-02 21:24 UTC, chrispader commented
Not completely finished yet though 😬

2022-07-04 17:09 UTC, gtokman commented
@chrispader the live pulse looks super nice!

2022-07-04 17:10 UTC, gtokman commented
Have you tried integrating a gradient? 

Saw some discussion here https://github.com/margelo/react-native-graph/issues/11#issuecomment-1119861429.

2022-07-18 09:07 UTC, chrispader commented
Not yet! Implemented a lot of features for use cases in one of our own projects at Margelo. I'll talk to @mrousavy on this. If i find some time, i may be implementing this for general use.

2022-08-31 19:35 UTC, Leoputera2407 commented
Hey Chris Pader, I was playing around with the Spline interpolation method you integration in this PR. I think it might not be implemented correctly, as there were a few of my datapoints with higher Y positions, got rendered lower

2022-08-31 20:05 UTC, chrispader commented
> Hey Chris Pader, I was playing around with the Spline interpolation method you integration in this PR. I think it might not be implemented correctly, as there were a few of my datapoints with higher Y positions, got rendered lower

Hi! Thanks for your input.

I already made some changes for a project for one of our clients, that address these issues..

I'll update this PR soon, so everhing works.

Sorry for the delay, kinda busy right now 😅😬

2022-08-31 23:42 UTC, Leoputera2407 commented
No worries, thanks for working on this!

2022-09-06 05:42 UTC, Leoputera2407 commented
@chrispader, are there any updates on this?

2022-09-06 09:03 UTC, chrispader commented
Not supposed to be closed, just an issue with squashing the commits. To be continued

2022-09-06 14:36 UTC, mrousavy requested changes

2022-09-06 14:36 UTC, mrousavy commented on src/CreateGraphPath.ts
> +
Please add explanation comments

2022-09-06 14:36 UTC, mrousavy commented on src/CreateGraphPath.ts
> +
Please add explanation comments

2022-09-06 14:36 UTC, mrousavy commented on src/LineGraphProps.ts
> +
Please add explanation comments

2022-09-06 14:36 UTC, mrousavy commented on src/utils/hexToRgba.ts
> +  if (alpha) {
```suggestion
  if (alpha > 0) {
```

2022-09-08 09:51 UTC, mrousavy requested changes
Looks good and runs very smoothly - nice work!

Left just a few code org comments to make it cleaner and easy to read, then we're good to go!

2022-09-08 09:51 UTC, mrousavy commented on example/src/screens/GraphPage.tsx
> +        }
Please move that into a `useMemo`. This ternary is way too complex, do clean and easy to read `if`s.

2022-09-08 09:51 UTC, mrousavy commented on example/src/screens/GraphPage.tsx
> +  const highestDate = useMemo(() => points[POINTS - 1]!.date, [])
Is it possible that this could be null in some cases? Do we need to check that? A `!` is always a bit risky...

2022-09-08 09:51 UTC, mrousavy commented on example/src/screens/GraphPage.tsx
> +                  min: points[0]!.date,
What if `points` is empty? This is null then

2022-09-08 09:51 UTC, mrousavy commented on src/CreateGraphPath.ts
> +    )
Maybe also split that into multiple vars, this is just too complex nested.

2022-09-08 10:16 UTC, mrousavy commented on example/src/screens/GraphPage.tsx
> +  }, [enableRange, highestDate, points])
I think this looks cleaner:
```suggestion
  const range: GraphRange | undefined = useMemo(() => {
    // if range is disabled, default to infinite range (undefined)
    if (!enableRange) return undefined
    
    if (points.length !== 0 && highestDate != null) {
      return {
        x: {
          min: points[0]!.date,
          max: new Date(highestDate.getTime() + 30),
        },
        y: {
          min: -200,
          max: 200,
        }
      }
    } else {
      return {
        y: {
          min: -200,
          max: 200
        }
      }
    }
  }, [enableRange, highestDate, points])
```

What do you think? (Hoping the logic is still the same, I haven't tested this!)

2022-09-08 10:20 UTC, mrousavy commented
LGTM! 🚀 nice work chris!

2022-09-08 10:20 UTC, merged