feat: add fill gradient to graph
margelo/react-native-graph pull request #41
Opened 2022-09-05 15:27 UTC by gtokman

Adds support for making a line with a fill gradient as mentioned in #11. 

### How
Pass in an extra prop type `gradientFillColors`:

```
<LineGraph
...
gradientFillColors={['#7476df5D', '#7476df4D', '#7476df00']}
```

### Result:

<img src='https://user-images.githubusercontent.com/12258850/188481083-ce13e23f-6122-4827-81c8-7cf9ff92f35a.png' width='250' />

2022-09-05 15:29 UTC, gtokman commented on example/src/screens/GraphPage.tsx
>          enablePanGesture={enablePanGesture}
I couldn't get the autocomplete to work for this prop.

2022-09-05 15:30 UTC, gtokman commented on src/AnimatedLineGraph.tsx
> +                      start={vec(0, 0)}
`path` here was causing a compiler warning and the same with `SelectionDot` below.

2022-09-06 12:59 UTC, mrousavy requested changes
Hey, thanks for your PR, this is really cool! Just left a few comments for a few code tweaks

2022-09-06 12:59 UTC, mrousavy commented on example/src/screens/GraphPage.tsx
> -    paddingHorizontal: 15,
Why?

2022-09-06 12:59 UTC, mrousavy commented on src/AnimatedLineGraph.tsx
> +  const makeFillGradient = gradientFillColors !== undefined
Let's rename this to `shouldFillGradient` and do `!= null` instead of `!== undefined` 🙏

2022-09-06 12:59 UTC, mrousavy commented on src/CreateGraphPath.ts
> +  makeFillGradient: boolean
Also rename here to `shouldFillGradient`

2022-09-06 12:59 UTC, mrousavy commented on src/LineGraphProps.ts
> +   * Colors for the fill gradient of the graph line
```suggestion
   * (Optional) Colors for the fill gradient below the graph line
```

2022-09-08 12:11 UTC, merged

2022-09-08 12:11 UTC, mrousavy commented
Wohoo! LGTM! Thanks Chris and @gtokman! ❤️